services:
  walletdriven_relyingparty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: walletdriven_relyingparty
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - {PATH_TO_JWT_CERTIFICATE_FOLDER}:{PATH_TO_JWT_CERTIFCATE_FOLDER_IN_CONTAINER}